In [2]:
from pyrqa.time_series import TimeSeries
from pyrqa.settings import Settings
from pyrqa.analysis_type import Classic
from pyrqa.neighbourhood import FixedRadius
from pyrqa.metric import EuclideanMetric
from pyrqa.computation import RQAComputation
data_points = [0.1, 0.5, 1.3, 0.7, 0.8, 1.4, 1.6, 1.2, 0.4, 1.1, 0.8, 0.2, 1.3]
time_series = TimeSeries(data_points,
                         embedding_dimension=2,
                         time_delay=2)
settings = Settings(time_series,
                    analysis_type=Classic,
                    neighbourhood=FixedRadius(0.65),
                    similarity_measure=EuclideanMetric,
                    theiler_corrector=1)
computation = RQAComputation.create(settings,
                                    verbose=True)
result = computation.run()
# result.min_diagonal_line_length = 2
# result.min_vertical_line_length = 2
# result.min_white_vertical_line_length = 2
print(result)

[Platform 'Apple']
Vendor: Apple
Version: OpenCL 1.2 (Feb 28 2021 03:51:16)
Profile: FULL_PROFILE
Extensions: cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event


[Device 'Apple M1']
Vendor: Intel
Type: 2
Version: OpenCL 1.2 
Profile: FULL_PROFILE
Max Clock Frequency: 2400
Global Mem Size: 8589934592
Address Bits: 64
Max Compute Units: 8
Max Work Group Size: 1024
Max Work Item Dimensions: 3
Max Work Item Sizes: [1024, 1, 1]
Local Mem Size: 32768
Max Mem Alloc Size: 2147483648
Extensions: cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_image2

In [9]:
from numpy import asarray
from sklearn.preprocessing import LabelEncoder
# define data
data = asarray([['cat'], ['dog'], ['turtle'], ['fish'], ['cat'], ['cat'], ['dog'], ['turtle'], ['fish'], ['cat']])
print(data)
# define one hot encoding
encoder = LabelEncoder()
# transform data
coded = encoder.fit_transform(data)
print(coded)

[['cat']
 ['dog']
 ['turtle']
 ['fish']
 ['cat']
 ['cat']
 ['dog']
 ['turtle']
 ['fish']
 ['cat']]
[0 1 3 2 0 0 1 3 2 0]


In [89]:
encoder.transform(data[data.team_id == data.team_id.unique()[1]]['Primary code '])

array([0, 5, 5, 8, 8, 8, 8, 5, 8, 8, 5, 8, 8, 8, 3, 8, 7, 8, 8, 5, 8, 5,
       8, 8, 8, 3, 5, 5, 8, 0, 0, 0, 8, 8, 8, 8, 6, 0, 1, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 7, 0, 0, 8, 8, 8, 8, 8, 8, 8, 8, 1, 7, 7, 6, 7, 7])

In [90]:
time_series_y.data

array([0., 5., 5., 8., 8., 8., 8., 5., 8., 8., 5., 8., 8., 8., 3., 8., 7.,
       8., 8., 5., 8., 5., 8., 8., 8., 3., 5., 5., 8., 0., 0., 0., 8., 8.,
       8., 8., 6., 0., 1., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 7., 0.,
       0., 8., 8., 8., 8., 8., 8., 8., 8., 1., 7., 7., 6., 7., 7.],
      dtype=float32)

In [85]:
from pyrqa.analysis_type import Cross
data_points_x = encoder.transform(data[data.team_id == data.team_id.unique()[0]]['Primary code '])
time_series_x = TimeSeries(data_points_x,
                           embedding_dimension=1,
                           time_delay=0)
data_points_y = encoder.transform(data[data.team_id == data.team_id.unique()[1]]['Primary code '])
time_series_y = TimeSeries(data_points_y,
                           embedding_dimension=1,
                           time_delay=0)
time_series = (time_series_x,
               time_series_x)
settings = Settings(time_series,
                    analysis_type=Cross,
                    neighbourhood=FixedRadius(0.5),
                    similarity_measure=EuclideanMetric,
                    theiler_corrector=0)
computation = RQAComputation.create(settings,
                                    verbose=True)
result = computation.run()
result.min_diagonal_line_length = 2
result.min_vertical_line_length = 2
result.min_white_vertical_line_length = 2
print(result)

[Platform 'Apple']
Vendor: Apple
Version: OpenCL 1.2 (Feb 28 2021 03:51:16)
Profile: FULL_PROFILE
Extensions: cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event


[Device 'Apple M1']
Vendor: Intel
Type: 2
Version: OpenCL 1.2 
Profile: FULL_PROFILE
Max Clock Frequency: 2400
Global Mem Size: 8589934592
Address Bits: 64
Max Compute Units: 8
Max Work Group Size: 1024
Max Work Item Dimensions: 3
Max Work Item Sizes: [1024, 1, 1]
Local Mem Size: 32768
Max Mem Alloc Size: 2147483648
Extensions: cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_image2

In [86]:
from pyrqa.computation import RPComputation
from pyrqa.image_generator import ImageGenerator
computation = RPComputation.create(settings)
result = computation.run()
ImageGenerator.save_recurrence_plot(result.recurrence_matrix_reverse,
                                    'cross_recurrence_plot.png')

In [87]:
result.recurrence_matrix_reverse

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=uint8)

In [33]:
import pandas as pd

In [115]:
data = pd.read_csv('/Users/amin/Downloads/Master Coded Data.xlsx - Chats.csv')

In [40]:
data.team_id.unique()[0]

'179706_162850_162936_182908'

In [42]:
data[data.team_id == data.team_id.unique()[0]]['Primary Sub-code']

0      SMC-R
1      SMC-R
2      SMC-R
3      SMC-R
4       CM-G
       ...  
77     SMC-R
78    SESU-A
79     SMC-R
80     SMC-R
81     SMC-R
Name: Primary Sub-code, Length: 82, dtype: object

In [80]:
from numpy import asarray
from sklearn.preprocessing import LabelEncoder
# define data
a = data['Primary code ']
# define one hot encoding
encoder = LabelEncoder()
# transform data
encoder.fit(a)
print(encoder.transform(data[data.team_id == data.team_id.unique()[0]]['Primary code ']))

[6 6 6 6 1 8 6 5 0 8 0 6 6 5 5 8 8 8 8 3 3 8 5 8 8 8 7 8 7 8 8 8 8 8 8 5 8
 5 8 0 8 0 7 7 0 8 8 8 8 8 8 8 0 8 8 8 8 8 1 7 8 8 8 7 8 5 5 1 8 1 8 5 7 0
 6 7 6 6 5 6 6 6]


In [93]:
len(data['Person-ID (mellon-ID)'].unique())

537

In [116]:
scores = pd.read_csv('/Users/amin/Downloads/CPS_scores.csv')

In [122]:
data = data.rename(columns={'Person-ID (mellon-ID)' : 'mellon_id'})

In [123]:
data

task                      team_id mellon_id  \
0     apartment  179706_162850_162936_182908    162850   
1     apartment  179706_162850_162936_182908    182908   
2     apartment  179706_162850_162936_182908    162936   
3     apartment  179706_162850_162936_182908    179706   
4     apartment  179706_162850_162936_182908    162850   
...         ...                          ...       ...   
7706  Candidate  190690_163721_178949_190068    186557   
7707  Candidate  190690_163721_178949_190069    186557   
7708  Candidate  190690_163721_178949_190070    165170   
7709  Candidate  190690_163721_178949_190071    190696   
7710  Candidate  190690_163721_178949_190072    183614   

               event_start_time             event_end_time       event_result  \
0     2019-09-28 17:14:21+00:00  2019-09-28 17:14:21+00:00                 Hi   
1     2019-09-28 17:14:39+00:00  2019-09-28 17:14:39+00:00                hey   
2     2019-09-28 17:14:47+00:00  2019-09-28 17:14:47+00:00                Hey   
3     2019-09-28 17:14:48+00:00  2019-09-28 17:14:48+00:00               hola   
4     2019-09-28 17:14:56+00:00  2019-09-28 17:14:56+00:00  Is everyone here?   
...                         ...                        ...                ...   
7706  2019-10-01 23:38:41+00:00                        NaN                 so   
7707  2019-10-01 23:38:43+00:00                        NaN               CBA?   
7708  2019-10-01 23:38:46+00:00                        NaN               yeah   
7709  2019-10-01 23:38:48+00:00                        NaN       I believe so   
7710  2019-10-01 23:38:53+00:00                        NaN             yes :)   

     Primary code  Primary Sub-code Secondary Code Secondary  Sub-code  ...  \
0              SMC            SMC-R            NaN                 NaN  ...   
1              SMC            SMC-R            NaN                 NaN  ...   
2              SMC            SMC-R            NaN                 NaN  ...   
3              SMC            SMC-R            NaN                 NaN  ...   
4               CM             CM-G            NaN                 NaN  ...   
...            ...              ...            ...                 ...  ...   
7706           SSI            SSI-U            NaN                 NaN  ...   
7707            CM             CM-S            NaN                 NaN  ...   
7708            SN             SN-A            NaN                 NaN  ...   
7709          SESU           SESU-A            NaN                 NaN  ...   
7710            SN             SN-A            NaN                 NaN  ...   

     Candidate Feature 3 Candidate Feature 4 Party Venue Feature 1  \
0                    NaN                 NaN                   NaN   
1                    NaN                 NaN                   NaN   
2                    NaN                 NaN                   NaN   
3                    NaN                 NaN                   NaN   
4                    NaN                 NaN                   NaN   
...                  ...                 ...                   ...   
7706                 NaN                 NaN                   NaN   
7707                 NaN                 NaN                   NaN   
7708                 NaN                 NaN                   NaN   
7709                 NaN                 NaN                   NaN   
7710                 NaN                 NaN                   NaN   

     Party Venue Feature 2 Party Venue Feature 3 Party Venue Feature 4  \
0                      NaN                   NaN                   NaN   
1                      NaN                   NaN                   NaN   
2                      NaN                   NaN                   NaN   
3                      NaN                   NaN                   NaN   
4                      NaN                   NaN                   NaN   
...                    ...                   ...                   ...   
7706                   NaN       

In [125]:
data_score = data.merge(scores, on=['mellon_id'], how = 'inner')

In [142]:
data_score

task_x                      team_id mellon_id  \
0     apartment  179706_162850_162936_182908    162850   
1     apartment  179706_162850_162936_182908    162850   
2     apartment  179706_162850_162936_182908    162850   
3     apartment  179706_162850_162936_182908    162850   
4     apartment  179706_162850_162936_182908    162850   
...         ...                          ...       ...   
7757  Candidate  190690_163721_178949_190053    165170   
7758  Candidate  190690_163721_178949_190054    165170   
7759  Candidate  190690_163721_178949_190058    165170   
7760  Candidate  190690_163721_178949_190065    165170   
7761  Candidate  190690_163721_178949_190070    165170   

               event_start_time             event_end_time  \
0     2019-09-28 17:14:21+00:00  2019-09-28 17:14:21+00:00   
1     2019-09-28 17:14:56+00:00  2019-09-28 17:14:56+00:00   
2     2019-09-28 17:15:44+00:00  2019-09-28 17:15:44+00:00   
3     2019-09-28 17:21:04+00:00  2019-09-28 17:21:04+00:00   
4     2019-09-28 17:21:30+00:00  2019-09-28 17:21:30+00:00   
...                         ...                        ...   
7757  2019-10-01 23:36:06+00:00                        NaN   
7758  2019-10-01 23:36:16+00:00                        NaN   
7759  2019-10-01 23:37:05+00:00                        NaN   
7760  2019-10-01 23:38:35+00:00                        NaN   
7761  2019-10-01 23:38:46+00:00                        NaN   

                                           event_result Primary code   \
0                                                    Hi           SMC   
1                                     Is everyone here?            CM   
2             Lets wait to see what the instructor says            CE   
3                                                   Hey           SMC   
4                                                 A B C           SSI   
...                                                 ...           ...   
7757                                            o snaap           SMC   
7758                       im shook can yall post yours            CE   
7759  wait it is suppose to be this way or is it a g...           SSI   
7760  I think w/ the new info, I think C is better t...           SSI   
7761                                               yeah            SN   

     Primary Sub-code Secondary Code Secondary  Sub-code  ...  \
0               SMC-R            NaN                 NaN  ...   
1                CM-G            NaN                 NaN  ...   
2               CEC-S            NaN                 NaN  ...   
3               SMC-R            NaN                 NaN  ...   
4               SSI-O            NaN                 NaN  ...   
...               ...            ...                 ...  ...   
7757            SMC-R            NaN                 NaN  ...   
7758            CEC-S            NaN                 NaN  ...   
7759            SSI-U            NaN                 NaN  ...   
7760            SSI-O            NaN                 NaN  ...   
7761             SN-A            NaN                 NaN  ...   

     Professor Feature 2 Professor Feature 3 Professor Feature 4 initial  \
0                    NaN                 NaN                 NaN     ABC   
1                    NaN                 NaN                 NaN     ABC   
2                    NaN                 NaN                 NaN     ABC   
3                    NaN                 NaN                 NaN     ABC   
4                    NaN                 NaN                 NaN     ABC   
...                  ...                 ...                 ...     ...   
7757                 NaN                 NaN                 NaN     BAC   
7758                 NaN                 NaN                 NaN     BAC   
7759                 NaN                 NaN                 NaN     BAC   
7760                 NaN                 NaN                 NaN     BAC   
7761                 NaN                 NaN                 NaN     BAC 

In [146]:
d1 = data_score.groupby(by=['team_id', 'mellon_id'], as_index=False).agg({'revise_score': 'mean'})

In [147]:
d2 = d1.groupby(by=['team_id'], as_index=False).agg({'revise_score': 'mean'})

In [154]:
d3 = data_score[['task_x', 'team_id', 'mellon_id', 'Primary code ']].merge(d2, on = ['team_id'])

In [156]:
np.mean(scores['revise_score'])

0.40671641791044777

In [157]:
mean = np.mean(d3['revise_score'])
high_perf = (d3['revise_score'] > mean).astype(int)

In [159]:
d3['high_performance'] = high_perf

In [160]:
d3

task_x                      team_id mellon_id Primary code   \
0     apartment  179706_162850_162936_182908    162850           SMC   
1     apartment  179706_162850_162936_182908    162850            CM   
2     apartment  179706_162850_162936_182908    162850            CE   
3     apartment  179706_162850_162936_182908    162850           SMC   
4     apartment  179706_162850_162936_182908    162850           SSI   
...         ...                          ...       ...           ...   
7757  Candidate  190690_163721_178949_190053    165170           SMC   
7758  Candidate  190690_163721_178949_190054    165170            CE   
7759  Candidate  190690_163721_178949_190058    165170           SSI   
7760  Candidate  190690_163721_178949_190065    165170           SSI   
7761  Candidate  190690_163721_178949_190070    165170            SN   

      revise_score  high_performance  
0              1.0                 1  
1              1.0                 1  
2              1.0                 1  
3              1.0                 1  
4              1.0                 1  
...            ...               ...  
7757           0.0                 0  
7758           0.0                 0  
7759           0.0                 0  
7760           0.0                 0  
7761           0.0                 0  

[7762 rows x 6 columns]

In [163]:
d3.to_csv('codes_scores_merged.csv')